# Generated by Django 4.2.7 on 2024-11-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('lyrics_content', models.TextField()),
                ('expert', models.CharField(max_length=255)),
                ('featuring_detail', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('genius_link', models.URLField()),
            ],
        ),
    ]
